name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
defaults:
  run:
    working-directory: maestrogateway
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3
      - name: Get Version-Tag
        id: yaml-data
        uses: jbutcher5/read-yaml@main
        with:
          file: './maestrogateway/config.yaml'
          key-path: '["version"]'
      - name: create image from repository
        run: docker build . --tag "ghcr.io/domhaas/maestrogateway-hassio:${{ steps.yaml-data.outputs.data }}"
      - name: push image to GitHub Container Registry
        run: docker push "ghcr.io/domhaas/maestrogateway-hassio:${{ steps.yaml-data.outputs.data }}"
